import React from 'react'
import Navbar from './Navbar'
import TableTitle from './TableTitle'
import Table from './Table'
import PasswordForm from './PasswordForm'

export default function Manager(props) {
    return (
        <>
            <head>
                <title>Password Manager | STACKS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <div>

                <Navbar userData={props.userData} />
                <div className="container">
                    <PasswordForm />
                    <TableTitle userData={props.userData} />

                    <Table />
                </div>

            </div>
        </>
    )
}
